# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rowan Gauld
title: Intermediate Software Engineer/Developer
email: rowangauld1@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: RowanG99
linkedin_username: Rowan Gauld

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I am a backend and devops engineer/developer that has experience in using modern and more mature technologies to solve problems within the context of software development and engineering. 
  I like to think that I don't just developer solutions, I engineer them. I am a firm believer that the software must not just work but it must work well, it needs to be tested thoroughly, optimized and refined. 
  I enjoy developing a variety of software, ranging from; scripts that automate processes, APIs, services, web applications and I dabble with software written in C such as interpreters, compilers and OS.

content:
  - title: Projects and Books
    layout: list
    content:
      - layout: top-middle
        title: The C Programming Language by Brain Kernighan and Dennies Richie
        link: link_to_be_inserted
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        #   # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   #   icon: fab fa-github
        #   #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          After my first year as a software engineer/developer, I realised that I'd like to learn more about the software that is used to make most software, C.
      
      - layout: top-middle
        title: Crafting Interpreters by Robert Nystrom
        link: link_to_be_inserted
        description: |
          After completing the book "The C Programming Languages" by Brain Kernighan and Dennies Richie, I wanted to apply what I have learnt and used this book as a guide for creating an interpreter.
      
      - layout: top-middle
        title: Learning Go with Pocket-Sized Projects by Aliénor Latour, Pascal Bertrand, Donia Chaiehloudj
        link: link_to_be_inserted
        description: |
          Thinking about what type of software I'd like to make in the future and what my current tool box contains, I thought Golang would be a great addition.

      - layout: top-middle
        title: C Interfaces and Implementations, Techniques for Creating Reusable Software
        link: link_to_be_inserted
        description: |
          Not only did I think this book would help me expand my knowledge in C but in programming and software engineering in general.

      - layout: top-middle
        title: Automate the Boring Stuff with Python by Al Sweigart
        link: link_to_be_inserted
        description: |
          I used this book to expand my Python knowledge.
  
  - title: Experience
    layout: list
    content:
      - layout: left
        title: BMW IT Hub
        link: https://www.bmwithub.co.za/
        sub_title: Junior Software Engineer
        caption: 2024-2026
        quote: >
          Intelligent Document Processing - Artificial Intelligence Platforms Department
        description: | # this will include new lines to allow paragraphs
            - Designed and developed key client facing APIs such as metric calculations and CRUD processes
            - Designed and developed internal APIs that ensured data in our database remained up to date and reliable
            - Designed and developed scripts and tooling relating to our CICD pipeline such creating or automatically renewed SSL certificates and uploaded them to AWS ACM, updating documentation relating to deployments, ensuring our runners had enough space and more
            - Designed and developed our unit testing environment
            - Responsible for our security posture, ensuring our application met compliance standards
        
        sub_title: Graduate
        caption: 2024-2026
        quote: >
          BMW IT Hub Graduate programme
        description: | # this will include new lines to allow paragraphs
            - Received training specific to AWS and obtained my AWS CP certification
            - Received training specific to Agile and CICD
            - Participated in internal hackathons such as developing a dashboard to view data relating to the movement of BMWs as the ownership changes from first hand owners to second hand owners

      - layout: left
        title: University of Pretoria
        link: https://www.up.ac.za/
        sub_title: Assistant Lecture
        caption: 2024-2026
        quote: >
          First year programming - Informatics Dept.
        description: | # this will include new lines to allow paragraphs
            - One of the assistant lecturers that led tutorial sessions

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
