repository: sproogen/resume-theme
favicon: images/favicon.ico

version: 2

name: Rowan Gauld
title: Intermediate Software Engineer/Developer

# Dark Mode (true/false/never)
darkmode: true

github_username: RowanG99
linkedin_username: www.linkedin.com/in/rowan-gauld

about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I am a backend and devops engineer/developer that has experience in using modern and more mature technologies to solve problems within the context of software development and engineering.
  I’d like to think that I don't just developer solutions, I engineer them. I am a firm believer that the software must not just work but it must work well.
  I enjoy developing a variety of software, ranging from; scripts that automate processes, APIs, services, web applications and I dabble with software written in C such as interpreters, compilers and OS.
  My toolbox consists of but is not limited to the following; Python, Go, C, Terraform, Bash and I can work with SQL and JS and I can use a wide range of other technologies such as AWS, Azure, Git and Docker.

content:  
  - title: Experience
    layout: list
    content:
      - layout: left
        title: BMW IT Hub
        link: https://www.bmwithub.co.za/
        quote: Intelligent Document Processing - Artificial Intelligence Platforms Department
        sub_title: Junior Software Engineer
        caption: 2024-2026
        description: | 
          - Designed and developed key client facing APIs such as metric calculations and CRUD processes
          - Designed and developed internal APIs that ensured data in our database remained up to date and reliable
          - Designed and developed scripts and tooling relating to our CICD pipeline such creating or automatically renewing SSL certificates and uploaded them to AWS ACM, updating documentation relating to deployments, ensuring our runners had enough space and more
          - Designed and developed our unit testing environment
          - Responsible for our security posture, ensuring our application met compliance standards

      - layout: left
        title: BMW IT Hub
        link: https://www.bmwithub.co.za/
        quote: BMW IT Hub Graduate programme
        sub_title: Graduate
        caption: 2023
        description: | 
          - Received training specific to AWS and obtained my AWS CP certification
          - Received training specific to Agile and CICD
          - Participated in internal hackathons such as developing a dashboard to view data relating to the movement of BMWs as the ownership changes from first hand owners to second hand owners

      - layout: left
        title: University of Pretoria
        link: https://www.up.ac.za/
        quote: First year programming - Informatics Dept.
        sub_title: Assistant Lecture
        caption: 2024-2026
        description: |
            - One of the assistant lecturers that led tutorial sessions

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Pretoria
        caption: 2022
        sub_title: BComHons Informatics
        description: |
          - Wrote a literature review paper on how NLP and other ML techniques could be used to extract data from documents.
          - Completed modules that relate to the following; enterprise architecture, data warehousing, data science, project management

      - layout: left
        title: University of Pretoria
        caption: 2019-2021
        sub_title: BCom Informatics
        description: |
          - Completed programming modules that focus on the use of C#, JS, SQL and R.
          - Completed theory modules that relate to system design, database design and management and project management
          - Completed modules that relate to statistics, internal auditing, data analysis
  
  - title: Projects and Books
    layout: list
    content:
      - layout: left
        title: The C Programming Language by Brain Kernighan and Dennies Richie
        link: link_to_be_inserted
        description: |
          After my first year as a software engineer/developer, I realised that I'd like to learn more about the software that is used to make most software, C.
      
      - layout: left
        title: Crafting Interpreters by Robert Nystrom
        description: |
          In Progress
        # description: |
        #   After completing the book "The C Programming Languages" by Brain Kernighan and Dennies Richie, I wanted to apply what I have learnt and used this book as a guide for creating an interpreter.
      
      - layout: left
        title: Learning Go with Pocket-Sized Projects by Aliénor Latour, Pascal Bertrand, Donia Chaiehloudj
        description: |
          In Progress
        # description: |
        #   Thinking about what type of software I'd like to make in the future and what my current tool box contains, I thought Golang would be a great addition.

      - layout: left
        title: C Interfaces and Implementations, Techniques for Creating Reusable Software
        description: |
          In Progress
        # description: |
        #   Not only did I think this book would help me expand my knowledge in C but in programming and software engineering in general.

      - layout: left
        title: Automate the Boring Stuff with Python by Al Sweigart
        description: |
          In Progress
        # description: |
        #   I used this book to expand my Python knowledge.


# Footer
# footer_show_references: true
references_title: Thank you, sproogen/resume-theme

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
